### ISSUE TITLE
Add tick method to CodeParser

### ISSUE THREAD

**Issue by rewolf93** [rewolf93/bee-racers#36]
Currently, the CodeParser uses a while loop to parse all of the assembly code. This won't work when we have multiple bees running together. Instead, we have to synchronize it to a clock. Add a `tick` method which takes no parameters. Every time `tick` is called, the VM/Parser should advance/execute the next instruction.

**Comment by Ryan-Sciarabba** [comment]
Tick method added. Will parse the current line of code and then increment lineNum
